'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clientes
    Public Property Id_cliente As Integer
    Public Property nombres As String
    Public Property apellidos As String
    Public Property dni As Integer
    Public Property domicilio As String
    Public Property telefono As String
    Public Property email As String
    Public Property fecharegistro As Date

    Public Overridable Property factura As ICollection(Of factura) = New HashSet(Of factura)

End Class
