'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class factura
    Public Property Id_factura As Integer
    Public Property cliente_id As Integer
    Public Property fecha As Date
    Public Property hora As System.TimeSpan
    Public Property vendedor_id As Integer
    Public Property forma_pago_id As Integer

    Public Overridable Property clientes As clientes
    Public Overridable Property factura_detalle As ICollection(Of factura_detalle) = New HashSet(Of factura_detalle)
    Public Overridable Property forma_pago As forma_pago
    Public Overridable Property usuarios As usuarios

End Class
