'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class factura_detalle
    Public Property Id_factura As Integer
    Public Property Id_factura_detalle As Integer
    Public Property producto_id As Integer
    Public Property cantidad As Integer
    Public Property precio_unit As Decimal

    Public Overridable Property factura As factura
    Public Overridable Property productos As productos

End Class
