'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class pcgamerEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=pcgamerEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property c1_procesador() As DbSet(Of c1_procesador)
    Public Overridable Property c2_placamadre() As DbSet(Of c2_placamadre)
    Public Overridable Property c3_ram() As DbSet(Of c3_ram)
    Public Overridable Property c4_placavideo() As DbSet(Of c4_placavideo)
    Public Overridable Property c5_discorigido() As DbSet(Of c5_discorigido)
    Public Overridable Property c6_gabinete() As DbSet(Of c6_gabinete)
    Public Overridable Property categoria() As DbSet(Of categoria)
    Public Overridable Property clientes() As DbSet(Of clientes)
    Public Overridable Property factura() As DbSet(Of factura)
    Public Overridable Property factura_detalle() As DbSet(Of factura_detalle)
    Public Overridable Property forma_pago() As DbSet(Of forma_pago)
    Public Overridable Property personas() As DbSet(Of personas)
    Public Overridable Property productos() As DbSet(Of productos)
    Public Overridable Property rol() As DbSet(Of rol)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property usuarios() As DbSet(Of usuarios)

End Class
