'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class personas
    Public Property Id_persona As Integer
    Public Property nombres As String
    Public Property apellidos As String
    Public Property email As String
    Public Property domicilio As String
    Public Property dni As Integer
    Public Property imagen As String
    Public Property rol_id As Integer
    Public Property telefono As String
    Public Property sexo As String

    Public Overridable Property rol As rol
    Public Overridable Property usuarios As ICollection(Of usuarios) = New HashSet(Of usuarios)

End Class
