'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class productos
    Public Property Id_producto As Integer
    Public Property nombre As String
    Public Property c1_procesador_id As Integer
    Public Property c2_placamadre_id As Integer
    Public Property c3_ram_id As Integer
    Public Property c4_placavideo_id As Integer
    Public Property c5_discorigido_id As Integer
    Public Property c6_gabinete_id As Integer
    Public Property precio As Decimal
    Public Property stock As Integer
    Public Property categoria_id As Integer
    Public Property imagen As String
    Public Property estado As Integer

    Public Overridable Property c1_procesador As c1_procesador
    Public Overridable Property c2_placamadre As c2_placamadre
    Public Overridable Property c3_ram As c3_ram
    Public Overridable Property c4_placavideo As c4_placavideo
    Public Overridable Property c5_discorigido As c5_discorigido
    Public Overridable Property c6_gabinete As c6_gabinete
    Public Overridable Property categoria As categoria
    Public Overridable Property factura_detalle As ICollection(Of factura_detalle) = New HashSet(Of factura_detalle)

End Class
