'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class rol
    Public Property Id_rol As Integer
    Public Property tipo_rol As String

    Public Overridable Property personas As ICollection(Of personas) = New HashSet(Of personas)

End Class
