'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuarios
    Public Property Id_usuario As Integer
    Public Property usuario As String
    Public Property contrasena As String
    Public Property persona_id As Integer
    Public Property estado As Integer
    Public Property fechaingreso As Date

    Public Overridable Property factura As ICollection(Of factura) = New HashSet(Of factura)
    Public Overridable Property personas As personas

    Friend Function nombre() As Object
        Throw New NotImplementedException()
    End Function
End Class
