'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("pcgamer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _63375334_representante_de_servicio_al_cliente_3d_ilustraci_n_aislado_sobre_fondo_blanco_Foto_de_archivo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("63375334-representante-de-servicio-al-cliente-3d-ilustraci-n-aislado-sobre-fondo-"& _ 
                        "blanco-Foto-de-archivo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acer_Aspire_E_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acer Aspire E 15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acer_Aspire_E_151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acer Aspire E 151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acer_Gamer_Vx15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acer-Gamer-Vx15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Acer_Gamer_Vx151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Acer-Gamer-Vx151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aero_500_BG_BK_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aero-500_BG_BK@2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almacen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almacen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property almacen2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("almacen2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property andrea() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("andrea", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property asus_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asus-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c69234e64fceb53934dd5c54b822075c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c69234e64fceb53934dd5c54b822075c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property can_stock_photo_csp13638182() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("can-stock-photo_csp13638182", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancelar_icono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar-icono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancelar_icono1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar-icono1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property candado_3d_8714068() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("candado-3d-8714068", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property candelaria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("candelaria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property carrito_agregar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carrito_agregar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property carrito_eliminar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carrito_eliminar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property circuit_planet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("circuit-planet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cirkuit_planet_8232_gamer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cirkuit-planet-8232-gamer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Client_Service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Client-Service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cliente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cliente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CORSAIR_GRAPHITE_230T_ORANGE_3FAN_LED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CORSAIR GRAPHITE 230T ORANGE 3FAN LED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Corsair_Spec_Alpha_Ventana_Usb3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Corsair-Spec-Alpha-Ventana-Usb3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property database_backup_icons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database-backup-icons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property database_backup_icons2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("database-backup-icons2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property donald_trump() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donald-trump", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property factura() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("factura", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property factura_icono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("factura-icono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property factura2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("factura2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property factura21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("factura21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property factura3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("factura3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property factura4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("factura4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gabinete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gabinete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gabinete_sentey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gabinete-sentey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gabinete_sentey1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gabinete-sentey1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gabinete1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gabinete1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gabinete2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gabinete2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gamer_Hp_Omen_15_ax205la() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gamer-Hp-Omen-15-ax205la", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gamer_Hp_Omen_15_ax205la1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gamer-Hp-Omen-15-ax205la1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hyperx_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hyperx-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icardi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icardi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property iceber_crystal_g5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iceber crystal g5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icerberg_turbo_z6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icerberg turbo z6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property informes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("informes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lupa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lupa_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupa-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lupa1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lupa1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marcelo_gallardo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marcelo-gallardo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property marcelo_tinelli() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("marcelo-tinelli", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notebook_bangho() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notebook-bangho", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notebook_bangho1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notebook-bangho1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nzxt_guardian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nzxt-guardian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nzxt_guardian1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nzxt-guardian1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property oie_transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("oie_transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ok_icono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok-icono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property okk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pcgamer_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pcgamer-logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pcgamer_logo_grande() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pcgamer-logo-grande", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pcgamer_logo_grande1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pcgamer-logo-grande1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pcgamer_logo_grande2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pcgamer-logo-grande2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pcgamer_logo_grande3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pcgamer-logo-grande3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pcgamer_readers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pcgamer-readers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property people_work_metaphor_separated_white_29812042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people-work-metaphor-separated-white-29812042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powercase_5263_gamer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powercase-5263-gamer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powercase_6813_gamer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powercase-6813-gamer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powercase_7041_gamer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powercase-7041-gamer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Riotoro_Cr_1280_prism_Full_Tower_Rgb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Riotoro-Cr-1280-prism-Full-Tower-Rgb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sama_Jax_01_Blanco___Rojo_120mm_Led() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sama-Jax-01-Blanco-&-Rojo-120mm-Led", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sama_Jax_01_Negro_Rojo_120mm_Led_Fan_Red_X_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sama-Jax-01-Negro-Rojo-120mm-Led-Fan-Red-X-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sentey_kron_gs_6005_1x80mm_1x120mm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sentey-kron-gs-6005-1x80mm-1x120mm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sin_imagen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sin-imagen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property steve_jobs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("steve-jobs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property super_admin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("super-admin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property super_admin1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("super-admin1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superadmin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superadmin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superadmin_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superadmin-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superadmin_background2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superadmin-background2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superadmin_background3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superadmin-background3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superadmin2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superadmin2.", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property THERMALTAKE_N21_GAMING__3_0__LED_ROJO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THERMALTAKE N21 GAMING (3,0) LED ROJO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property THERMALTAKE_N21_GAMING__3_0__LED_ROJO1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THERMALTAKE N21 GAMING (3,0) LED ROJO1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermaltake_Versa_C21_Rgb_Mid_Tower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermaltake-Versa-C21-Rgb-Mid-Tower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Thermaltake_Versa_C22_Rgb_Ventana_Cooler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Thermaltake-Versa-C22-Rgb-Ventana-Cooler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property THERMALTAKE_VERSA_H22__3_0_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THERMALTAKE VERSA H22 (3,0)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property THERMALTAKE_VERSA_H22__3_0_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("THERMALTAKE VERSA H22 (3,0)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property usuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wanda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wanda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Yiyo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Yiyo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
